// What HQPlayer 6 says about each filter and modulator, for v5 instances, which
// don't describe their own. Matched by name; v5.17.2's lists equal v6's apart from
// the entries marked v5-only. Ratio rules are NOT taken from here: v5 follows the
// v5 manual's table in compat.ts. See README "Where filter descriptions come from".
//
// Source: the descriptions HQPlayer 6 Embedded (engine 6.2.3) sends to control
// apps, per mode. [rating out of 5, focus tags]; v5-only entries have no rating.

export type Described = [rating: number | null, tags: string[]];

/**
 * In v5 but not v6, so HQPlayer 6 doesn't describe them: focus from the v5.13
 * manual's §4.6 table, restated; no rating, because the manual gives none.
 */
const V5_ONLY: Record<string, Described> = {
  "poly-sinc-ext3": [null, ["timbre"]],
  "poly-sinc-gauss": [null, ["transients", "timbre"]],
};

/** v5-only modulators, in our words from the v5.13 manual §4.5. */
export const MODULATOR_NOTE: Record<string, string> = {
  AHM5EC5L: "experimental five-level; lower SNR, so not for when HQPlayer's volume is your main volume control",
  AHM7EC5L: "experimental five-level; lower SNR, so not for when HQPlayer's volume is your main volume control",
};

export const FILTERS_V6: Record<"sdm" | "pcm", Record<string, Described>> = {
  sdm: {
    IIR: [2, []],
    IIR2: [4, []],
    FIR: [3, []],
    asymFIR: [3, []],
    minphaseFIR: [3, []],
    FFT: [4, []],
    "poly-sinc-lp": [4, ["space"]],
    "poly-sinc-mp": [4, ["transients"]],
    "poly-sinc-short-lp": [3, ["transients", "space"]],
    "poly-sinc-short-mp": [3, ["transients"]],
    "poly-sinc-long-lp": [4, ["space"]],
    "poly-sinc-long-ip": [4, ["space", "transients"]],
    "poly-sinc-long-mp": [4, ["transients"]],
    "poly-sinc-hb": [4, []],
    "poly-sinc-hb-xs-2s": [2, []],
    "poly-sinc-hb-s-2s": [3, []],
    "poly-sinc-hb-m-2s": [3, []],
    "poly-sinc-hb-l-2s": [4, []],
    "poly-sinc-ext": [3, []],
    "poly-sinc-ext2": [5, ["timbre"]],
    "poly-sinc-ext2-short": [4, ["timbre"]],
    "poly-sinc-ext2-medium": [4, ["timbre"]],
    "poly-sinc-ext2-long": [5, ["timbre"]],
    "poly-sinc-ext2-xla": [5, ["timbre"]],
    "poly-sinc-ext2-xl": [5, ["timbre"]],
    "poly-sinc-ext2-hires-lp": [5, ["timbre"]],
    "poly-sinc-ext2-hires-ip": [5, ["timbre"]],
    "poly-sinc-ext2-hires-mp": [5, ["timbre"]],
    "poly-sinc-mqa/mp3-lp": [4, ["transients"]],
    "poly-sinc-mqa/mp3-mp": [4, ["transients"]],
    "poly-sinc-xtr-lp": [5, ["timbre"]],
    "poly-sinc-xtr-mp": [5, ["timbre"]],
    "poly-sinc-xtr-short-lp": [5, ["timbre", "transients"]],
    "poly-sinc-xtr-short-mp": [5, ["timbre", "transients"]],
    "poly-sinc-lp-2s": [4, ["space"]],
    "poly-sinc-mp-2s": [4, ["transients"]],
    "poly-sinc-short-lp-2s": [3, ["transients", "space"]],
    "poly-sinc-short-mp-2s": [3, ["transients"]],
    "poly-sinc-long-lp-2s": [4, ["space"]],
    "poly-sinc-long-ip-2s": [4, ["space", "transients"]],
    "poly-sinc-long-mp-2s": [4, ["transients"]],
    "poly-sinc-hb-2s": [4, []],
    "poly-sinc-xtr-lp-2s": [5, ["timbre"]],
    "poly-sinc-xtr-mp-2s": [5, ["timbre"]],
    "poly-sinc-xtr-short-lp-2s": [5, ["timbre", "transients"]],
    "poly-sinc-xtr-short-mp-2s": [5, ["timbre", "transients"]],
    "poly-sinc-gauss-short": [3, ["transients"]],
    "poly-sinc-gauss-medium": [4, ["transients", "timbre"]],
    "poly-sinc-gauss-long": [5, ["transients", "timbre", "space"]],
    "poly-sinc-gauss-xla": [5, ["transients", "timbre", "space"]],
    "poly-sinc-gauss-xl": [5, ["transients", "timbre", "space"]],
    "poly-sinc-gauss-hires-lp": [5, ["transients", "timbre", "space"]],
    "poly-sinc-gauss-hires-ip": [5, ["transients", "timbre", "space"]],
    "poly-sinc-gauss-hires-mp": [5, ["transients", "timbre", "space"]],
    "poly-sinc-gauss-halfband": [4, ["transients", "timbre", "space"]],
    "poly-sinc-gauss-halfband-s": [3, ["transients", "timbre", "space"]],
    "polynomial-1": [1, []],
    "polynomial-2": [1, []],
    "minringFIR-lp": [2, ["transients"]],
    "minringFIR-mp": [2, ["transients"]],
    "closed-form": [3, []],
    "closed-form-fast": [2, []],
    "closed-form-16M": [3, []],
    "sinc-S": [4, ["space", "timbre"]],
    "sinc-M": [4, ["space", "timbre"]],
    "sinc-Mx": [4, ["space", "timbre"]],
    "sinc-MG": [4, ["transients", "timbre", "space"]],
    "sinc-MGa": [4, ["transients", "timbre", "space"]],
    "sinc-L": [3, []],
    "sinc-Ls": [2, []],
    "sinc-Lm": [2, []],
    "sinc-Ll": [3, []],
    "sinc-Lh": [4, []],
    "sinc-short": [2, []],
    "sinc-medium": [2, []],
    "sinc-long": [3, []],
    "sinc-long-h": [4, []],
    ...V5_ONLY,
  },
  pcm: {
    none: [1, []],
    IIR: [2, []],
    IIR2: [4, []],
    FIR: [3, []],
    asymFIR: [3, []],
    minphaseFIR: [3, []],
    FFT: [4, []],
    "poly-sinc-lp": [4, ["space"]],
    "poly-sinc-mp": [4, ["transients"]],
    "poly-sinc-short-lp": [3, ["space", "transients"]],
    "poly-sinc-short-mp": [3, ["transients"]],
    "poly-sinc-long-lp": [4, ["space"]],
    "poly-sinc-long-ip": [4, ["space", "transients"]],
    "poly-sinc-long-mp": [4, ["transients"]],
    "poly-sinc-hb": [4, []],
    "poly-sinc-hb-xs": [2, []],
    "poly-sinc-hb-s": [3, []],
    "poly-sinc-hb-m": [3, []],
    "poly-sinc-hb-l": [4, []],
    "poly-sinc-ext": [3, []],
    "poly-sinc-ext2": [5, ["timbre"]],
    "poly-sinc-ext2-short": [4, ["timbre"]],
    "poly-sinc-ext2-medium": [4, ["timbre"]],
    "poly-sinc-ext2-long": [5, ["timbre"]],
    "poly-sinc-ext2-xla": [5, ["timbre"]],
    "poly-sinc-ext2-xl": [5, ["timbre"]],
    "poly-sinc-ext2-hires-lp": [5, ["timbre"]],
    "poly-sinc-ext2-hires-ip": [5, ["timbre"]],
    "poly-sinc-ext2-hires-mp": [5, ["timbre"]],
    "poly-sinc-mqa/mp3-lp": [4, ["transients"]],
    "poly-sinc-mqa/mp3-mp": [4, ["transients"]],
    "poly-sinc-xtr-lp": [5, ["timbre"]],
    "poly-sinc-xtr-mp": [5, ["timbre"]],
    "poly-sinc-xtr-short-lp": [5, ["timbre"]],
    "poly-sinc-xtr-short-mp": [5, ["timbre"]],
    "poly-sinc-gauss-short": [3, ["transients"]],
    "poly-sinc-gauss-medium": [4, ["transients", "timbre"]],
    "poly-sinc-gauss-long": [5, ["transients", "timbre", "space"]],
    "poly-sinc-gauss-xla": [5, ["transients", "timbre", "space"]],
    "poly-sinc-gauss-xl": [5, ["transients", "timbre", "space"]],
    "poly-sinc-gauss-hires-lp": [5, ["transients", "timbre", "space"]],
    "poly-sinc-gauss-hires-ip": [5, ["transients", "timbre", "space"]],
    "poly-sinc-gauss-hires-mp": [5, ["transients", "timbre", "space"]],
    "poly-sinc-gauss-halfband": [4, ["transients", "timbre", "space"]],
    "poly-sinc-gauss-halfband-s": [3, ["transients", "timbre", "space"]],
    ASRC: [2, []],
    "polynomial-1": [1, []],
    "polynomial-2": [1, []],
    "minringFIR-lp": [2, ["transients"]],
    "minringFIR-mp": [2, ["transients"]],
    "closed-form": [3, []],
    "closed-form-fast": [2, []],
    "closed-form-M": [3, []],
    "sinc-S": [4, ["space", "timbre"]],
    "sinc-M": [4, ["space", "timbre"]],
    "sinc-Mx": [4, ["space", "timbre"]],
    "sinc-MG": [4, ["transients", "timbre", "space"]],
    "sinc-MGa": [4, ["transients", "timbre", "space"]],
    "sinc-L": [3, []],
    "sinc-Ls": [2, []],
    "sinc-Lm": [2, []],
    "sinc-Ll": [3, []],
    "sinc-Lh": [4, []],
    "sinc-short": [2, []],
    "sinc-medium": [2, []],
    "sinc-long": [3, []],
    "sinc-long-h": [4, []],
    ...V5_ONLY,
  },
};

/** Modulator generation (HQPlayer 6's "GenN"). */
export const MODULATOR_GEN: Record<string, number> = {
  DSD5: 1,
  DSD5v2: 2,
  "DSD5v2 256+fs": 2,
  DSD5EC: 4,
  ASDM5: 3,
  ASDM5EC: 4,
  ASDM5ECv2: 5,
  ASDM5ECv3: 6,
  "ASDM5EC-ul": 7,
  "ASDM5EC-light": 7,
  "ASDM5EC-fast": 7,
  "ASDM5EC-super": 7,
  "ASDM5EC-ul 512+fs": 7,
  "ASDM5EC-light 512+fs": 7,
  "ASDM5EC-fast 512+fs": 7,
  "ASDM5EC-super 512+fs": 7,
  DSD7: 2,
  "DSD7 256+fs": 2,
  ASDM7: 3,
  ASDM7EC: 4,
  ASDM7ECv2: 5,
  ASDM7ECv3: 6,
  "ASDM7EC-ul": 7,
  "ASDM7EC-light": 7,
  "ASDM7EC-fast": 7,
  "ASDM7EC-super": 7,
  "ASDM7EC-ul 512+fs": 7,
  "ASDM7EC-light 512+fs": 7,
  "ASDM7EC-fast 512+fs": 7,
  "ASDM7EC-super 512+fs": 7,
  "AMSDM7 512+fs": 3,
  "AMSDM7EC 512+fs": 4,
  AHM5EC4B: 8,
  AHM7EC4B: 8,
  AHM5EC8B: 8,
  AHM7EC8B: 8,
};
